// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClGMF7FBoDK3k6fUBEGCULYvum0wfv004',
    appId: '1:323924073046:web:d70e4e71a6c84cc1f739f7',
    messagingSenderId: '323924073046',
    projectId: 'project-retali',
    authDomain: 'project-retali.firebaseapp.com',
    storageBucket: 'project-retali.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSLRB_Sdg6YGGxXOUFogTbJVTB7wZImlE',
    appId: '1:323924073046:android:74562f260e06dc41f739f7',
    messagingSenderId: '323924073046',
    projectId: 'project-retali',
    storageBucket: 'project-retali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6WgIlGE8o_UfDH_T5MqAWQ70l2Ho4lM',
    appId: '1:323924073046:ios:f1870498e59f8fabf739f7',
    messagingSenderId: '323924073046',
    projectId: 'project-retali',
    storageBucket: 'project-retali.firebasestorage.app',
    iosBundleId: 'com.example.mobileRetali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6WgIlGE8o_UfDH_T5MqAWQ70l2Ho4lM',
    appId: '1:323924073046:ios:f1870498e59f8fabf739f7',
    messagingSenderId: '323924073046',
    projectId: 'project-retali',
    storageBucket: 'project-retali.firebasestorage.app',
    iosBundleId: 'com.example.mobileRetali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClGMF7FBoDK3k6fUBEGCULYvum0wfv004',
    appId: '1:323924073046:web:6f827c691f4a99fef739f7',
    messagingSenderId: '323924073046',
    projectId: 'project-retali',
    authDomain: 'project-retali.firebaseapp.com',
    storageBucket: 'project-retali.firebasestorage.app',
  );
}
